apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: snow-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snow
  template:
    metadata:
      labels:
        app: snow
    spec:
      containers:
        - name: snowflake
          image: vadimsavchuk/my-repo:snowflake-2.1 # локальный snowflake:1.0 не работает с кластером kind нужен удаленный образ
          env: # используем Downward API, чтобы прокинуть данные о pod внутрь контейнера как переменные окружения
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/management/health/liveness"
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/management/health/readiness"
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
