apiVersion: v1
kind: Pod
metadata:
  name: snow
spec:
  containers:
    - image: snowflake:1.0
      name: snowflake
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
